/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	T_n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	P_n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	H_n=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
 */
package Java;

import java.util.*;

public class Problem45
{
    private static long tri(long n)
    {
        return n*(n+1)/2;
    }

    private static long pent(long n)
    {
        return n*(3*n-1)/2;
    }

    private static long hex(long n)
    {
        return n*(2*n-1);
    }

    public static void main(String[] args)
    {
        List<Long> trilist = new ArrayList<Long>();
        List<Long> pentlist = new ArrayList<Long>();
        List<Long> hexlist = new ArrayList<Long>();

        for (long i = 0; i < 1000000; i++)
        {
            trilist.add(tri(i));
            pentlist.add(pent(i));
            hexlist.add(hex(i));
        }

        int index = hexlist.indexOf((long)40755);

        for (int i = index+1; i < hexlist.size(); i++)
        {
            long num = hexlist.get(i);
            if (trilist.contains(num) && pentlist.contains(num))
            {
                System.out.println(num);
                break;
            }
        }
    }
}
