"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	T_n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	P_n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	H_n=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def main():
    #set up functions to generate the different sequences
    tri = lambda n: n*(n+1)/2
    pent = lambda n: n*(3*n-1)/2
    hex = lambda n: n*(2*n-1)

    triset,pentset,hexset = list(),list(),list()

    #populate the sets
    for i in range(1,1000000):
        triset.append(tri(i))
        pentset.append(pent(i))
        hexset.append(hex(i))


    index = hexset.index(40755) #only iterate over one of the sets rather than naive iteration to improve speed
    
    for i in range(index+1,len(hexset)):
        num = hexset[i]
        if num in triset and num in pentset: #check if number is also in those lists
            print(num)
            break

if __name__ == "__main__":
    main()